<?php

namespace AppBundle\Repository;

/**
 * GymLocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GymLocationRepository extends \Doctrine\ORM\EntityRepository
{

//    public function getGymLocationForUserQuery(){
//
//    }



}
