<?php

namespace AppBundle\Repository;

/**
 * GymRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GymRepository extends \Doctrine\ORM\EntityRepository
{
}
