<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;

/**
 * GymRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GymRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Returns All Gyms for User
     *
     * @param User $user
     *
     * @return array
     */
    public function getAllGymsForUserQuery(User $user){
        $query = $this->createQueryBuilder('gym')
            ->where('gym.user = :user')
            ->setParameter('user', $user)
            ->getQuery();

        return $query->getResult();

    }


}
