<?php

namespace AppBundle\Repository;

/**
 * PartnerRequestPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartnerRequestPostRepository extends \Doctrine\ORM\EntityRepository
{
}
