<?php

namespace AppBundle\Repository;

/**
 * PostLocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostLocationRepository extends \Doctrine\ORM\EntityRepository
{
}
