<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Returns all posts for the user
     *
     * @param User $user
     *
     * @return array
     */
    public function getAllPostsForUserQuery(User $user){
        $query = $this->createQueryBuilder('post')
            ->where('post.user = :user')
            ->setParameter('user', $user)
            ->addOrderBy('post.dateCreated', 'DESC')
            ->getQuery();

        return $query->getResult();

    }
}
