<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;

/**
 * RecordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecordRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get all Records for the given user
     *
     * @param User $user
     * @return array
     */
    public function getAllRecordsForUser(User $user){
        $query = $this->createQueryBuilder('record')
            ->where('record.user = :user')
            ->setParameter('user', $user)
            ->addOrderBy('record.dateCreated', 'DESC')
            ->getQuery();

        return $query->getResult();
    }

}
